modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
[[mods]] #mandatory
	modId="CustomOreGen" #mandatory
	version="${version}" #mandatory
	displayName="Custom Ore Generation" #mandatory
	authors="JRoush, noogenesis"
	description='''
	Allows the player to customize how ore is generated.
	'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/customoregen"
	logoFile="/Logo.png"
	credits="Thanks to marcopolo1613, Cadde, mossman1223, reteo, Draco18s."
	[[dependencies.CustomOreGen]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[27,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.CustomOreGen]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.3,)"
	    ordering="NONE"
	    side="BOTH"
